version: '3'
services:
    app:
        build: .
        volumes:
            - ./app:/app
        ports:
            - "3000:3000"
        tty: true
        environment:
            - DEBUG=app:*
        command: sh -c "npm install && /bin/sh"