version: '3'
services:
    app:
        build:
            context: "./"
            dockerfile: "Dockerfile_mac"
        volumes:
            # マウントの高速化
            - ./app:/app
            # Volume Trick
            - exclude_node_modules:/app/node_modules
        ports:
            - "3000:3000"
            - "3001:3001"
            - "4000:4000"
        tty: true
        environment:
            - DEBUG=app:*
            # nodemonがファイル変更を検知するために必要
            - CHOKIDAR_USEPOLLING=1
            # この2行で日時を設定
            - LD_PRELOAD=/usr/local/lib/faketime/libfaketimeMT.so.1

        command: /bin/bash -c "npm run start-dev"
volumes:
    exclude_node_modules:
