version: '3'
services:
    app:
        build: .
        # image: my_node1
        volumes:
            - ./app:/app
        ports:
            - "3000:3000"
        tty: true
        environment:
            - DEBUG=app:*
        command: npm start