version: '3'
services:
    app:
        build: .
        volumes:
            - ./app:/app
        ports:
            - "3000:3000"
            - "3001:3001"
            - "4000:4000"
        tty: true
        environment:
            - DEBUG=app:*
        # この2行で日時を設定
            - LD_PRELOAD=/usr/local/lib/faketime/libfaketimeMT.so.1

        command: /bin/sh -c "npm install && npm run start-dev"
